import streamlit as st
if 'Year' in df.columns and filters['value_col'] is not None:
    st.subheader("Time series by Year")
    ts = df.groupby('Year')[filters['value_col']].mean().reset_index()
    fig = px.line(ts, x='Year', y=filters['value_col'], markers=True,
                  title=f"Average {filters['value_col']} by Year")
    st.plotly_chart(fig, use_container_width=True)



# Top regions bar chart
if filters['region_col'] and filters['value_col'] is not None:
st.subheader("Top Dzongkhags by value")
agg = df.groupby(filters['region_col'])[filters['value_col']].mean().reset_index()
agg = agg.sort_values(filters['value_col'], ascending=False).head(15)
fig2 = px.bar(agg, x=filters['region_col'], y=filters['value_col'], title=f"Top Dzongkhags: {filters['value_col']}")
st.plotly_chart(fig2, use_container_width=True)


# Scatter / indicator comparisons
st.subheader("Scatter: compare two numeric columns")
numeric_cols = df.select_dtypes(include=['number']).columns.tolist()
if len(numeric_cols) >= 2:
x_col = st.selectbox("X axis", options=numeric_cols, index=0)
y_col = st.selectbox("Y axis", options=numeric_cols, index=1)
scatter = df.dropna(subset=[x_col, y_col])
fig3 = px.scatter(scatter, x=x_col, y=y_col, hover_data=scatter.columns, title=f"{y_col} vs {x_col}")
st.plotly_chart(fig3, use_container_width=True)
else:
st.info("Not enough numeric columns to show scatter plot.")




def download_button(df: pd.DataFrame):
csv = df.to_csv(index=False).encode('utf-8')
st.download_button(label="Download filtered data as CSV", data=csv, file_name=f"filtered_health_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv", mime='text/csv')




def main():
st.set_page_config(page_title="Bhutan Health Indicators", layout="wide")
st.title("Bhutan — Health Indicators Dashboard")


try:
df = load_data(CSV_PATH)
except FileNotFoundError:
st.error(f"CSV file not found at {CSV_PATH}. Please upload or change CSV_PATH.")
uploaded = st.file_uploader("Upload health_indicators_btn.csv", type=["csv"])
if uploaded is not None:
df = pd.read_csv(uploaded)
df.columns = [c.strip() for c in df.columns]
else:
st.stop()


filters = sidebar_filters(df)
filtered = apply_filters(df, filters)


# Layout: left column for overview, right for charts
left, right = st.columns([1,2])
with left:
show_overview(filtered)
download_button(filtered)


with right:
show_charts(filtered, filters)


st.markdown("---")
st.caption("App generated by ChatGPT — edit the script to match exact column names and desired visuals.")


if __name__ == '__main__':
main()
